@extends('layouts.app')
@section('title',$item['title'])
@section('content')
@push('styles')
<script type="application/ld+json">{!! json_encode(['@context'=>'https://schema.org','@type'=>'TouristAttraction','name'=>$item['title'],'description'=>$item['seo_description'],'image'=>array_values(array_filter(array_merge([$item['image']],$item['gallery'] ?? []))),'address'=>$item['address'],'url'=>route('tourism.show',$item['slug']),'geo'=>($item['latitude'] !== null && $item['longitude'] !== null) ? ['@type'=>'GeoCoordinates','latitude'=>$item['latitude'],'longitude'=>$item['longitude']] : null], JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE) !!}</script>
@endpush
<section class="tourism-detail-hero"><img src="{{ $item['image'] }}" alt="{{ $item['title'] }}"><div class="tourism-detail-overlay"></div><div class="shell"><a class="tourism-back" href="{{ route('tourism') }}"><i class="ri-arrow-left-line"></i> Semua wisata</a><span class="eyebrow light">{{ $item['tagline'] }}</span><h1>{{ $item['title'] }}</h1><p><i class="ri-map-pin-2-line"></i>{{ $item['address'] }}</p></div></section>
<section class="section"><div class="shell tourism-detail-layout"><article class="tourism-story"><span class="eyebrow">Tentang destinasi</span><h2>Sebuah pengalaman dari {{ $name }}</h2><div class="rich-copy">{!! str_contains($item['description'],'<') ? $item['description'] : nl2br(e($item['description'])) !!}</div>
@if(count($item['activities'] ?? []))<div class="tourism-feature-block"><h3>Aktivitas yang dapat dilakukan</h3><div class="tourism-chip-grid">@foreach($item['activities'] as $activity)<span><i class="ri-walk-line"></i>{{ $activity }}</span>@endforeach</div></div>@endif
@if(count($item['facilities'] ?? []))<div class="tourism-feature-block"><h3>Fasilitas tersedia</h3><div class="tourism-chip-grid">@foreach($item['facilities'] as $facility)<span><i class="ri-checkbox-circle-line"></i>{{ $facility }}</span>@endforeach</div></div>@endif
@if(count($item['tourism_services'] ?? []))<div class="tourism-feature-block"><span class="eyebrow">Layanan & paket</span><h3>Pilih pengalaman Anda</h3><div class="tourism-service-grid">@foreach($item['tourism_services'] as $service)<article><i class="ri-tent-line"></i><div><strong>{{ str_contains($service,'—') ? trim(explode('—',$service,2)[0]) : $service }}</strong>@if(str_contains($service,'—'))<small>{{ trim(explode('—',$service,2)[1]) }}</small>@endif</div></article>@endforeach</div></div>@endif
@if(!empty($item['booking_instructions']))<div class="tourism-feature-block tourism-booking-steps"><span class="eyebrow">Cara booking</span><h3>Reservasi kunjungan</h3><div class="rich-copy">{!! str_contains($item['booking_instructions'],'<') ? $item['booking_instructions'] : nl2br(e($item['booking_instructions'])) !!}</div></div>@endif
<div class="visitor-note"><i class="ri-information-line"></i><div><strong>Rencanakan kunjungan Anda</strong><p>Hubungi pengelola sebelum berangkat untuk memastikan kondisi akses, jam kunjungan, dan kebutuhan pendampingan.</p></div></div></article>
<aside class="tourism-plan-card"><span>RENCANAKAN KUNJUNGAN</span><h3>Siap menjelajah?</h3><div class="tourism-plan-row"><i class="ri-map-pin-line"></i><div><small>Lokasi</small><strong>{{ $item['address'] }}</strong></div></div>@if($item['contact'])<div class="tourism-plan-row"><i class="ri-whatsapp-line"></i><div><small>Kontak pengelola</small><strong>{{ $item['contact'] }}</strong></div></div>@endif
@if($item['opening_hours'])<div class="tourism-plan-row"><i class="ri-time-line"></i><div><small>Jam operasional</small><strong>{{ $item['opening_hours'] }}</strong></div></div>@endif
@if($item['ticket_price'])<div class="tourism-plan-row"><i class="ri-ticket-2-line"></i><div><small>Harga tiket</small><strong>{{ $item['ticket_price'] }}</strong></div></div>@endif
@if($item['latitude'] && $item['longitude'])<a class="button primary tourism-full-button" href="https://www.google.com/maps/search/?api=1&query={{ $item['latitude'] }},{{ $item['longitude'] }}" target="_blank" rel="noopener"><i class="ri-navigation-line"></i> Buka petunjuk arah</a>@endif
@if($item['booking_url'])<a class="button primary tourism-full-button" href="{{ $item['booking_url'] }}" target="_blank" rel="noopener"><i class="ri-calendar-check-line"></i> Reservasi kunjungan</a>@endif
@if($item['contact'])<a class="button tourism-whatsapp tourism-full-button" href="https://wa.me/{{ $item['contact'] }}?text={{ urlencode('Halo, saya ingin menanyakan informasi kunjungan ke '.$item['title']) }}" target="_blank" rel="noopener"><i class="ri-whatsapp-line"></i> Hubungi pengelola</a>@endif</aside></div></section>
@if(count($item['gallery'] ?? []))<section class="section muted"><div class="shell"><div class="section-head"><div><span class="eyebrow">Galeri destinasi</span><h2>Lihat lebih dekat</h2></div></div><div class="tourism-gallery">@foreach($item['gallery'] as $photo)<figure><img src="{{ $photo }}" alt="{{ $item['title'] }}" loading="lazy"></figure>@endforeach</div></div></section>@endif
<section class="section muted"><div class="shell"><div class="section-head"><div><span class="eyebrow">Lanjut menjelajah</span><h2>Destinasi lainnya</h2></div><a class="text-link" href="{{ route('tourism') }}">Lihat semua <i class="ri-arrow-right-line"></i></a></div><div class="tourism-grid compact">@foreach(collect($tourism)->where('slug','!=',$item['slug'])->take(3) as $related)<article class="tourism-card"><a class="tourism-card-image" href="{{ route('tourism.show',$related['slug']) }}"><img src="{{ $related['image'] }}" alt="{{ $related['title'] }}" loading="lazy"></a><div><h3>{{ $related['title'] }}</h3><a class="text-link" href="{{ route('tourism.show',$related['slug']) }}">Lihat destinasi <i class="ri-arrow-right-line"></i></a></div></article>@endforeach</div></div></section>
@endsection
@push('styles')
<style>.tourism-feature-block{margin-top:34px}.tourism-feature-block h3{font-size:22px}.tourism-chip-grid,.tourism-service-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.tourism-chip-grid span{display:flex;align-items:center;gap:8px;padding:12px;border:1px solid var(--line);border-radius:10px;color:var(--muted)}.tourism-chip-grid i{color:var(--green2);font-size:19px}.tourism-service-grid article{display:flex;align-items:center;gap:12px;padding:16px;border:1px solid var(--line);border-radius:12px;background:#fff}.tourism-service-grid article>i{display:grid;width:42px;height:42px;flex:0 0 42px;place-items:center;border-radius:10px;background:#e6f4ef;color:var(--green2);font-size:21px}.tourism-service-grid article div{display:flex;flex-direction:column}.tourism-service-grid small{color:var(--muted)}.tourism-booking-steps ol{padding:0;list-style:none}.tourism-booking-steps li{display:flex;align-items:flex-start;gap:12px;margin:12px 0}.tourism-booking-steps li>span{display:grid;width:30px;height:30px;flex:0 0 30px;place-items:center;border-radius:50%;background:var(--green2);color:#fff;font-weight:800}.tourism-booking-steps p{margin:4px 0;color:var(--muted)}.tourism-gallery{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.tourism-gallery figure{overflow:hidden;margin:0;border-radius:14px}.tourism-gallery img{height:300px;transition:.35s}.tourism-gallery img:hover{transform:scale(1.035)}@media(max-width:700px){.tourism-chip-grid,.tourism-service-grid,.tourism-gallery{grid-template-columns:1fr}.tourism-gallery img{height:250px}}</style>
@endpush
